name: Telegram News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la
