name: Cron Test

on:
  workflow_dispatch:
  schedule:
    - cron: "4,14,24,34,44,54 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check trigger
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          date -u
